project:
  type: website
  
website:
  cookie-consent:
    type: express
    style: simple
    palette: dark
  google-analytics:
    tracking-id: "G-PDNERYD0X5"
    anonymize-ip: true

  navbar:
    background: "transparent"
    foreground: "black"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Contact
      - href: gallery.qmd
        text: Gallery
  page-footer: 
    background: "transparent"
    foreground: "black"
    left: "Copyright 2025" 
    right: 
      - icon: linkedin
        href: linkedin.com/in/fazilasadia
      - icon: github 
        href: https://github.com/fazilasadia
      - icon: email
        href: fazila.sadia@gmail.com     

format:
  html:
    css: styles.css
    toc: false
    include-in-header: 
      #my-header-scripts.html
      gtm_code_head.html
    include-after-body: my-footer-scripts.html
